### ISSUE TITLE
Img styles are not properly included making profile image embeds display incorrectly

### ISSUE THREAD

**Issue by Stvad** [rhinobase/react-bluesky#7]
<img width="727" alt="image" src="https://github.com/user-attachments/assets/d5e324a5-1171-4637-8127-6ef0377e8a8d" />

If I add the CSS file provided by the package - it seems like the styles for img are missing/misconfigured resulting in profile image not displaying correctly

The profile image display starts working correctly if I copy the following style from the docs page:
```css
img, video {
    max-width: 100%;
    height: auto;
}
```
